#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Script to extract cpu utilization values from mpstat log.

Usage: $0 MPSTAT_LOG_FILE

"""

import sys

CPU_LOG_INTERVAL_IN_SECS = 3


def main():
    iowait_idx = -1
    idle_idx = -1

    cpu_utils = []

    with open(CPUSTAT_LOG_FILE, 'rt') as filep:
        for line in filep:
            if iowait_idx < 0 or idle_idx < 0:
                if '%iowait' in line:
                    headers = line.split()
                    iowait_idx = headers.index('%iowait')
                    idle_idx = headers.index('%idle')
            elif 'Average' not in line and 'all' in line:
                values = line.split()
                cpu_utils.append(
                    float(values[iowait_idx]) + float(values[idle_idx]))

    with open('cpu_utils.csv', 'wt') as filep:
        seconds = 0
        for util_val in cpu_utils:
            filep.write(str(seconds) + ',' + str(100 - util_val) + ',\n')
            seconds += CPU_LOG_INTERVAL_IN_SECS


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("""\
Usage: {} MPSTAT_LOG_FILE

MPSTAT_LOG_FILE:
    The log file generated by MPSTAT(1)
""".format(sys.argv[0]))
        exit(1)

    CPUSTAT_LOG_FILE = sys.argv[1]
    main()
