#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Script to extract system wide physical memory utilizations from vmstat log.

Usage: $0 SYSTEM_MEM_KB VMSTAT_LOG_FILE

"""

import sys

MEM_LOG_INTERVAL_IN_SECS = 3


def main():
    mem_utils = []

    with open(VMSTAT_LOG_FILE, 'rt') as filep:
        for line in filep:
            if ':' in line:
                values = line.split()
                mem_utils.append(
                    SYSTEM_MEM_KB -
                    int(values[3]) -
                    int(values[4]) -
                    int(values[5]))

    with open('mem_utils.csv', 'wt') as filep:
        seconds = 0
        for util_val in mem_utils:
            filep.write(str(seconds) + ',' + str(util_val) + ',\n')
            seconds += MEM_LOG_INTERVAL_IN_SECS


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("""\
Usage: {} SYSTEM_MEM_KB VMSTAT_LOG_FILE

SYSTEM_MEM_KB:
    This is the system installed physical memory (MemTotal in /proc/meminfo)

VMSTAT_LOG_FILE:
    The log file generated by VMSTAT(8)
""".format(sys.argv[0]))
        exit(1)

    SYSTEM_MEM_KB = int(sys.argv[1])
    VMSTAT_LOG_FILE = sys.argv[2]
    main()
